// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuaqD6tU2PGmC9j2dzAWJVPyYEdECM2-E',
    appId: '1:803186490275:web:bd6605b913d19cca0bf816',
    messagingSenderId: '803186490275',
    projectId: 'flutterauthen-b57a1',
    authDomain: 'flutterauthen-b57a1.firebaseapp.com',
    storageBucket: 'flutterauthen-b57a1.appspot.com',
    measurementId: 'G-8BWTSF4WHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLXwkD2290VDHTmr4H4_NZylabtuOpD4M',
    appId: '1:803186490275:android:f9994ead82bf334f0bf816',
    messagingSenderId: '803186490275',
    projectId: 'flutterauthen-b57a1',
    storageBucket: 'flutterauthen-b57a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComAPB6YcDNLYchc9gY3pjWdj20-Lcg7Q',
    appId: '1:803186490275:ios:211919605aa3130d0bf816',
    messagingSenderId: '803186490275',
    projectId: 'flutterauthen-b57a1',
    storageBucket: 'flutterauthen-b57a1.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyComAPB6YcDNLYchc9gY3pjWdj20-Lcg7Q',
    appId: '1:803186490275:ios:39692e21994685c50bf816',
    messagingSenderId: '803186490275',
    projectId: 'flutterauthen-b57a1',
    storageBucket: 'flutterauthen-b57a1.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
